services:
  - type: web
    name: stagechat-signaling
    env: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 4000
      - key: ADMIN_PASSWORD
        value: As66773707
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"